### ISSUE TITLE
Issue with unstable_vitePlugin

### ISSUE THREAD

**Issue by hauptrolle** [sergiodxa/remix-i18next#161] opened 2023-11-01 09:56 UTC
### Describe the bug

When using the new `unstable_vitePlugin` the dev server and build failes with the following error:

`10:54:31 AM [vite] Error when evaluating SSR module /app/lib/i18n/i18next.server.ts: failed to import "remix-i18next"`

```
export * from "./client";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

### Steps to Reproduce the Bug or Issue

Us the new `unstable_vitePlugin`

### Expected behavior

It does not throw an error.

**Comment by DavoCg** [comment] 2023-11-01 13:12
Hi @hauptrolle, I'm facing the same issue, I don't know Vite very well but it seems that using : 

```js
export default defineConfig({
  plugins: [remix(), tsconfigPaths()],
  ssr: {
    noExternal: ["remix-i18next"],
  },
});
```
makes this specific error you are mentioning disappear but introduces another error : 

```bash
TypeError: headers.get is not a function
    at Module.getClientLocales (/Users/davo/dev/dials/node_modules/remix-i18next/browser/lib/get-client-locales.js:7:34)
```

I'll keep an eye on this issue to see if someone comes with a good fix.

**Comment by xHomu** [comment] 2023-11-01 21:18
As a temporary fix, try 

`import { RemixI18Next } from "node_modules/remix-i18next/browser/server.js";` and etc if this is a blocker for your vite migration.

**Comment by brandonpittman** [comment] 2023-11-07 01:55
I'm seeing another issue with remix-i18n where Vite chokes on `accept-language-parser` and its use of `module.exports` syntax.

```sh
10:51:44 AM [vite] Error when evaluating SSR module /node_modules/accept-language-parser/index.js?v=caa3510c:
ReferenceError: module is not defined
    at /node_modules/accept-language-parser/index.js?v=caa3510c:73:1
    at instantiateModule (/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:15)
```

**Comment by xHomu** [comment] 2023-11-07 02:06
I was recommended this Vite plugin, see if this solves it for you https://github.com/cyco130/vite-plugin-cjs-interop

**Comment by brandonpittman** [comment] 2023-11-07 02:13
I solved the `accept-language-parser` by inlining the `pick` function into `remix-i18n`.

**Comment by brandonpittman** [comment] 2023-11-07 02:13
Now I'm seeing this:

```sh
TypeError: headers.get is not a function
    at Module.getClientLocales (/node_modules/remix-i18next/browser/lib/get-client-locales.js:7:34)
```

**Comment by grinkus-adapt** [comment] 2023-11-07 06:29
> Now I'm seeing this:
> 
> ```shell
> TypeError: headers.get is not a function
>     at Module.getClientLocales (/node_modules/remix-i18next/browser/lib/get-client-locales.js:7:34)
> ```

Seems like what's discussed in https://github.com/remix-run/remix/issues/7819

**Comment by djhi** [comment] 2023-11-18 05:25
I don't have this issue anymore after upgrading remix to `2.3.0` and vite to `5.0.0`.

Still using this configuration:
```
export default defineConfig({
  plugins: [remix(), tsconfigPaths()],
  ssr: {
    noExternal: ["remix-i18next"],
  },
});
```

**Comment by pimjansen** [comment] 2023-12-11 19:30
> ```shell
> TypeError: headers.get is not a function
>     at Module.getClientLocales (/node_modules/remix
> ```

This seems resolved in the 2.4.0 pre-release of remix/dev however it seems that the Server script returns an error

```
TypeError: __vite_ssr_import_2__.Response is not a constructor
    at onShellReady (/home/pim/projects/onderwijscatalogus/frontend/app/entry.server.tsx:59:13)
    at finishedTask (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6513:7)
    at retryTask (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6598:5)
    at performWork (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6642:7)
    at Immediate._onImmediate (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6969:12)
    at process.processImmediate (node:internal/timers:476:21)
TypeError: __vite_ssr_import_2__.Response is not a constructor
    at onShellReady (/home/pim/projects/onderwijscatalogus/frontend/app/entry.server.tsx:59:13)
    at finishedTask (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6513:7)
    at retryTask (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6598:5)
    at performWork (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6642:7)
    at Immediate._onImmediate (/home/pim/projects/onderwijscatalogus/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6969:12)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by aniforprez** [comment] 2023-12-22 19:55
As of writing this, the issue is not presenting itself with remix 2.4.0. Seems like it's been fixed and the solution is to upgrade remix.

**Closed** 2024-01-11 16:22 UTC

**Comment by sbaechler** [comment] 2024-01-15 17:02
It still requires the `noExternal` config to run with Remix 2.5.

```javascript
export default defineConfig({
  plugins: [remix(), tsconfigPaths()],
  ssr: {
    noExternal: ["remix-i18next"],
  },
});
```
